// main.js - Editor Logic

import Papa from "https://cdn.jsdelivr.net/npm/papaparse@5/+esm";

import { EmitContext, ForceFunc, LimitFunc, BlendFunc } from './emit_context.js';
import { EmitSequence } from './emit_sequence.js';

import { EmitBuilder, ToolMode } from './emit_builder.js';

window.emitSequence = null;
window.currentEmits = null;
window.currentEmitIndex = 0;

const ICON_UP_CARET = '&#9650;';
const ICON_DOWN_CARET = '&#9660;';
const ICON_COPY_CODE = '&#x2398;';
const ICON_DUPLICATE = '&#128203;';
const ICON_CLOSE = '&#x2715;';

const DEFAULT_TEMPO = 60;

const TEMPLATE_SCRIPT = `-- Generated by Vis editor
Vis = require('Vis')
VisUtil = require('visutil')
Emit = require('emit')

local BASE = _G.BASE or 0 -- Update to the base offset to the first emit

`;

document.addEventListener('DOMContentLoaded', () => {
    // Editor state
    let currentToolMode = ToolMode.SQUARE;
    let currentTimeMs = 0; // State variable to track the currently edited time
    let fps = 30; // Frames per second
    let showAxes = true; // State for axes visibility

    let dragMode = false;
    let nativeMode = false;
    let canvasW = 800; // Initial canvas width
    let canvasH = 600; // Initial canvas height
    let clipboardFrame = null; // Stores serialized context list for copying/pasting frames
    let tempo = DEFAULT_TEMPO;
    let timeFormat = 'ms';
    let customScript = TEMPLATE_SCRIPT;

    // Sequence to store all generated emits mapped by time
    window.emitSequence = new EmitSequence();

    const canvas = document.getElementById('editor-canvas');
    const ctx = canvas.getContext('2d');
    const workspace = document.getElementById('workspace');

    // Theta modal elements
    const thetaModal = document.getElementById('theta-modal');
    const thetaCanvas = document.getElementById('theta-canvas');
    const thetaSlider = document.getElementById('theta-slider');
    const thetaRadians = document.getElementById('theta-radians');
    const thetaDegrees = document.getElementById('theta-degrees');
    const uthetaSlider = document.getElementById('utheta-slider');
    const uthetaRadians = document.getElementById('utheta-radians');
    const uthetaDegrees = document.getElementById('utheta-degrees');

    // The current array of emit contexts being edited/generated for the active frame
    window.currentEmits = [new EmitBuilder(canvas, canvasW, canvasH)];
    window.currentEmitIndex = 0; // Tracks which emit in currentEmits is actively being edited

    let undoStack = [];
    let redoStack = [];

    let isDraggingCanvas = false;
    let lastDragPos = null;

    // UI controls
    const btnTimePrev = document.getElementById('btn-time-prev');
    const btnTimeNext = document.getElementById('btn-time-next');
    const btnTimeSeekPrev = document.getElementById('btn-time-seek-prev');
    const btnTimeSeekNext = document.getElementById('btn-time-seek-next');
    const inputTime = document.getElementById('input-time');
    const selectFps = document.getElementById('select-fps');
    const labelFrame = document.getElementById('label-frame');
    const inputCanvasW = document.getElementById('input-canvas-w');
    const inputCanvasH = document.getElementById('input-canvas-h');
    const statusCursor = document.getElementById('status-cursor');
    const inputFrameName = document.getElementById('input-frame-name');
    const inputFrameOffset = document.getElementById('input-frame-offset');
    const inputTempo = document.getElementById('input-tempo');
    const selectTimeFormat = document.getElementById('select-time-format');

    function saveStateForUndo(customData = {}) {
        const state = {
            time: currentTimeMs,
            emits: currentEmits.map(b => b.ctx.toJSON()),
            index: currentEmitIndex,
            name: emitSequence.getNameAt(currentTimeMs),
            ...customData
        };
        undoStack.push(state);
        redoStack = [];
    }

    function performUndo() {
        if (undoStack.length === 0) return;
        saveCurrentFrame();
        const state = undoStack.pop();
        redoStack.push({
            time: currentTimeMs,
            emits: currentEmits.map(b => b.ctx.toJSON()),
            index: currentEmitIndex,
            name: emitSequence.getNameAt(currentTimeMs),
            deletedFrameTime: state.deletedFrameTime !== undefined ? state.time : undefined
        });

        if (state.deletedFrameTime !== undefined) {
            emitSequence.deleteAt(state.deletedFrameTime);
        }

        currentTimeMs = state.time;
        currentEmits = state.emits.map(data => {
            const builder = new EmitBuilder(canvas, canvasW, canvasH);
            builder.ctx = EmitContext.FromJSON(data);
            return builder;
        });
        currentEmitIndex = state.index;
        emitSequence.setNameAt(currentTimeMs, state.name);
        inputFrameName.value = state.name || "";
        inputFrameOffset.value = Math.round(state.time);
        saveCurrentFrame();
        updateTimeUI();
        updateLayerDisplay();
        requestAnimationFrame(draw);
    }

    function performRedo() {
        if (redoStack.length === 0) return;
        saveCurrentFrame();
        const state = redoStack.pop();
        undoStack.push({
            time: currentTimeMs,
            emits: currentEmits.map(b => b.ctx.toJSON()),
            index: currentEmitIndex,
            name: emitSequence.getNameAt(currentTimeMs),
            deletedFrameTime: state.deletedFrameTime !== undefined ? state.time : undefined
        });

        if (state.deletedFrameTime !== undefined) {
            emitSequence.deleteAt(state.deletedFrameTime);
        }

        currentTimeMs = state.time;
        currentEmits = state.emits.map(data => {
            const builder = new EmitBuilder(canvas, canvasW, canvasH);
            builder.ctx = EmitContext.FromJSON(data);
            return builder;
        });
        currentEmitIndex = state.index;
        emitSequence.setNameAt(currentTimeMs, state.name);
        inputFrameName.value = state.name || "";
        inputFrameOffset.value = Math.round(state.time);
        saveCurrentFrame();
        updateTimeUI();
        updateLayerDisplay();
        requestAnimationFrame(draw);
    }

    // Resize canvas to fit the workspace
    function resizeCanvas() {
        canvas.width = workspace.clientWidth;
        canvas.height = workspace.clientHeight;
        for (let emit of window.currentEmits) {
            emit.canvasW = workspace.clientWidth;
            emit.canvasH = workspace.clientHeight;
        }
    }

    // Initial resize
    window.addEventListener('resize', resizeCanvas);
    resizeCanvas();

    inputFrameName.addEventListener('input', (e) => {
        emitSequence.setNameAt(currentTimeMs, e.target.value);
        updateTimeline();
    });

    inputFrameOffset.addEventListener('change', (e) => {
        const newTime = parseFloat(e.target.value);
        if (isNaN(newTime) || newTime < 0 || newTime === currentTimeMs) {
            e.target.value = Math.round(currentTimeMs);
            return;
        }

        saveStateForUndo({ deletedFrameTime: newTime });

        const currentName = emitSequence.getNameAt(currentTimeMs);
        const copiedEmits = currentEmits.map(builder => {
            const b = new EmitBuilder(canvas, canvasW, canvasH);
            b.ctx = EmitContext.FromJSON(builder.ctx.toJSON());
            return b;
        });

        emitSequence.deleteAt(currentTimeMs);
        emitSequence.setEmitsAt(newTime, copiedEmits);
        if (currentName) {
            emitSequence.setNameAt(newTime, currentName);
        }

        currentTimeMs = newTime;
        loadCurrentFrame();
        updateTimeUI();
    });

    inputCanvasW.addEventListener('change', (e) => {
        canvasW = parseInt(e.target.value, 10) || 800;
        console.log(`Canvas width set to ${canvasW}`);
        for (const builder of currentEmits) {
            builder.resize(canvasW, canvasH);
        }
        requestAnimationFrame(draw);
    });

    inputCanvasH.addEventListener('change', (e) => {
        canvasH = parseInt(e.target.value, 10) || 600;
        console.log(`Canvas height set to ${canvasH}`);
        for (const builder of currentEmits) {
            builder.resize(canvasW, canvasH);
        }
        requestAnimationFrame(draw);
    });

    // Keyboard Events
    // Note: the canvas has tabindex="0" so it can receive focus for key events
    document.addEventListener('keydown', (e) => {
        console.log(`Key down: ${e.key} (Code: ${e.code})`);

        if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 's') {
            e.preventDefault();
            document.getElementById('btn-save').click();
        } else if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 'o') {
            e.preventDefault();
            openJsonFile();
        } else if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 'e') {
            e.preventDefault();
            document.getElementById('btn-export').click();
        } else if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 'z') {
            e.preventDefault();
            document.getElementById('btn-undo').click();
        } else if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 'y') {
            e.preventDefault();
            document.getElementById('btn-redo').click();
        } else if ((e.ctrlKey || e.shiftKey) && e.key.toLowerCase() === 'i') {
            e.preventDefault();
            document.getElementById('btn-import-timing').click();
        } else if (e.key === 'Delete' || e.key === 'Backspace') {
            const activeTag = document.activeElement ? document.activeElement.tagName.toLowerCase() : '';
            if (activeTag === 'input' || activeTag === 'textarea' || activeTag === 'select') {
                return; // Do not delete layer if user is typing in an input field
            }
            if (currentEmitIndex !== null && currentEmits[currentEmitIndex]) {
                saveStateForUndo();
                const index = currentEmitIndex;
                currentEmits.splice(index, 1);
                currentEmitIndex = Math.max(0, index - 1);
                updateLayerDisplay();
                requestAnimationFrame(draw);
            }
        } else if (e.key === 'ArrowLeft') {
            const activeTag = document.activeElement ? document.activeElement.tagName.toLowerCase() : '';
            if (activeTag === 'input' || activeTag === 'textarea' || activeTag === 'select') {
                return;
            }
            e.preventDefault();
            document.getElementById('btn-time-seek-prev').click();
        } else if (e.key === 'ArrowRight') {
            const activeTag = document.activeElement ? document.activeElement.tagName.toLowerCase() : '';
            if (activeTag === 'input' || activeTag === 'textarea' || activeTag === 'select') {
                return;
            }
            e.preventDefault();
            document.getElementById('btn-time-seek-next').click();
        }
    });

    function updateLayerDisplay() {
        const layerList = document.getElementById('layer-list');
        if (!layerList) return;
        layerList.innerHTML = '';

        if (currentEmits.length === 0) {
            const emptyMsg = document.createElement('div');
            emptyMsg.style.padding = '8px 16px';
            emptyMsg.style.color = 'var(--text-color)';
            emptyMsg.style.opacity = '0.5';
            emptyMsg.style.fontSize = '14px';
            emptyMsg.style.fontStyle = 'italic';
            emptyMsg.textContent = 'No layers';
            layerList.appendChild(emptyMsg);
            return;
        }

        // Draw each layer window
        currentEmits.forEach((layer, idx) => {
            const item = document.createElement('div');
            item.className = 'layer-item';
            if (idx === currentEmitIndex) {
                item.classList.add('selected');
            }

            const title = document.createElement('div');
            title.className = 'layer-title';

            const titleText = document.createElement('span');
            titleText.textContent = `${idx === currentEmitIndex ? '>' : ' '} Layer ${idx}`;
            titleText.style.flex = '1';

            const copyCodeBtn = document.createElement('button');
            copyCodeBtn.innerHTML = ICON_COPY_CODE;
            copyCodeBtn.title = 'Copy Code to Clipboard';
            copyCodeBtn.style.background = 'none';
            copyCodeBtn.style.border = 'none';
            copyCodeBtn.style.color = 'inherit';
            copyCodeBtn.style.cursor = 'pointer';
            copyCodeBtn.style.padding = '0 4px';
            copyCodeBtn.style.opacity = '0.6';

            copyCodeBtn.addEventListener('mouseenter', () => copyCodeBtn.style.opacity = '1');
            copyCodeBtn.addEventListener('mouseleave', () => copyCodeBtn.style.opacity = '0.6');

            copyCodeBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                const codeString = layer.ctx.serialize(
                    nativeMode,
                    currentTimeMs,
                    true,
                    window.emitSequence.getNameAt(currentTimeMs));
                navigator.clipboard.writeText(codeString).then(() => {
                    console.log('Code copied to clipboard.');
                }).catch(err => {
                    console.error('Failed to copy code: ', err);
                });
            });

            const duplicateBtn = document.createElement('button');
            duplicateBtn.innerHTML = ICON_DUPLICATE;
            duplicateBtn.title = 'Duplicate Layer';
            duplicateBtn.style.background = 'none';
            duplicateBtn.style.border = 'none';
            duplicateBtn.style.color = 'inherit';
            duplicateBtn.style.cursor = 'pointer';
            duplicateBtn.style.padding = '0 4px';
            duplicateBtn.style.opacity = '0.6';

            duplicateBtn.addEventListener('mouseenter', () => duplicateBtn.style.opacity = '1');
            duplicateBtn.addEventListener('mouseleave', () => duplicateBtn.style.opacity = '0.6');

            duplicateBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                saveStateForUndo();
                const newBuilder = new EmitBuilder(canvas, canvasW, canvasH);
                newBuilder.ctx = EmitContext.FromJSON(layer.ctx.toJSON());
                currentEmits.splice(idx + 1, 0, newBuilder);
                currentEmitIndex = idx + 1;
                updateLayerDisplay();
                requestAnimationFrame(draw);
            });

            const closeBtn = document.createElement('button');
            closeBtn.innerHTML = ICON_CLOSE;
            closeBtn.title = 'Delete Layer';
            closeBtn.style.background = 'none';
            closeBtn.style.border = 'none';
            closeBtn.style.color = 'inherit';
            closeBtn.style.cursor = 'pointer';
            closeBtn.style.padding = '0 4px';
            closeBtn.style.opacity = '0.6';

            closeBtn.addEventListener('mouseenter', () => closeBtn.style.opacity = '1');
            closeBtn.addEventListener('mouseleave', () => closeBtn.style.opacity = '0.6');

            closeBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                saveStateForUndo();
                currentEmits.splice(idx, 1);
                if (currentEmits.length === 0) {
                    currentEmitIndex = null;
                } else if (currentEmitIndex === idx) {
                    currentEmitIndex = Math.min(currentEmitIndex, currentEmits.length - 1);
                } else if (currentEmitIndex > idx) {
                    currentEmitIndex--;
                }
                updateLayerDisplay();
                requestAnimationFrame(draw);
            });

            title.appendChild(titleText);
            title.appendChild(copyCodeBtn);
            title.appendChild(duplicateBtn);
            title.appendChild(closeBtn);

            const codeContainer = document.createElement('div');
            codeContainer.className = 'layer-code-container';

            const code = document.createElement('code');
            code.className = 'layer-code';
            code.classList.toggle('collapsed');

            const toggleBtn = document.createElement('button');
            toggleBtn.className = 'layer-code-toggle';
            toggleBtn.innerHTML = ICON_DOWN_CARET;

            toggleBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                code.classList.toggle('collapsed');
                toggleBtn.innerHTML = code.classList.contains('collapsed') ? ICON_DOWN_CARET : ICON_UP_CARET;
                if (idx === currentEmitIndex) {
                    code.textContent = layer.ctx.serialize(
                        nativeMode,
                        currentTimeMs,
                        code.classList.contains('collapsed'),
                        window.emitSequence.getNameAt(currentTimeMs));
                }
            });

            if (idx === currentEmitIndex) {
                code.textContent = layer.ctx.serialize(
                    nativeMode,
                    currentTimeMs,
                    code.classList.contains('collapsed'),
                    window.emitSequence.getNameAt(currentTimeMs));
            }

            codeContainer.appendChild(code);
            codeContainer.appendChild(toggleBtn);

            item.appendChild(title);
            item.appendChild(codeContainer);

            if (idx === currentEmitIndex) {
                const controls = document.createElement('div');
                controls.style.display = 'flex';
                controls.style.flexDirection = 'column';
                controls.style.marginTop = '8px';
                controls.style.gap = '4px';

                const config = [
                    { name: 'count', min: 0, step: 1 },
                    { name: 'x', min: -canvasW/2, max: canvasW/2, step: 1 },
                    { name: 'y', min: -canvasH/2, max: canvasH/2, step: 1 },
                    { name: 'ux', min: 0, max: canvasW, step: 1 },
                    { name: 'uy', min: 0, max: canvasH, step: 1 },
                    { name: 's', min: 0, max: Math.max(canvasW, canvasH), step: 1 },
                    { name: 'us', min: 0, max: Math.max(canvasW, canvasH), step: 1 },
                    { name: 'ds', step: 0.1 },
                    { name: 'uds', step: 0.1 },
                    { name: 'radius', min: 1, step: 1 },
                    { name: 'uradius', min: 0, step: 1 },
                    { name: 'theta', min: 0, max: 2 * Math.PI, step: 0.01 },
                    { name: 'utheta', min: 0, max: Math.PI, step: 0.01 },
                    { name: 'life', min: 0, step: 1 },
                    { name: 'ulife', min: 0, step: 1 },
                    { name: 'rgb', type: 'color' },
                    { name: 'ur', min: 0, max: 1, step: 0.01 },
                    { name: 'ug', min: 0, max: 1, step: 0.01 },
                    { name: 'ub', min: 0, max: 1, step: 0.01 },
                    { name: 'depth', step: 1 },
                    { name: 'force', type: 'select', options: Object.keys(ForceFunc).map(k => ({text: k, value: ForceFunc[k]})) },
                    { name: 'limit', type: 'select', options: Object.keys(LimitFunc).map(k => ({text: k, value: LimitFunc[k]})) },
                    { name: 'blender', type: 'select', options: Object.keys(BlendFunc).map(k => ({text: k, value: BlendFunc[k]})) },
                    { name: 'tag', min: 0, step: 1 }
                ];

                for (const c of config) {
                    const row = document.createElement('div');
                    row.style.display = 'flex';
                    row.style.justifyContent = 'space-between';

                    const lbl = document.createElement('label');
                    lbl.classList.add('layer-label');
                    lbl.textContent = c.name;

                    if (c.name === 'theta' || c.name === 'utheta') {
                        lbl.classList.add('clickable-label');
                        lbl.title = 'Click to configure angle & spread';
                        lbl.addEventListener('click', () => {
                            openThetaModal(layer, code);
                        });
                    }

                    let inp;

                    if (c.type === 'color') {
                        inp = document.createElement('input');
                        inp.type = 'color';
                        const toHex = val => Math.round(Math.max(0, Math.min(1, val)) * 255).toString(16).padStart(2, '0');
                        inp.value = `#${toHex(layer.ctx.r)}${toHex(layer.ctx.g)}${toHex(layer.ctx.b)}`;

                        inp.addEventListener('input', (e) => {
                            const hex = e.target.value;
                            layer.ctx.r = parseInt(hex.slice(1,3), 16) / 255.0;
                            layer.ctx.g = parseInt(hex.slice(3,5), 16) / 255.0;
                            layer.ctx.b = parseInt(hex.slice(5,7), 16) / 255.0;
                            code.textContent = layer.ctx.serialize(
                                nativeMode,
                                currentTimeMs,
                                code.classList.contains('collapsed'),
                                window.emitSequence.getNameAt(currentTimeMs));
                            requestAnimationFrame(draw);
                        });
                    } else if (c.type === 'select') {
                        inp = document.createElement('select');
                        for (const opt of c.options) {
                            const o = document.createElement('option');
                            o.value = opt.value;
                            o.textContent = opt.text;
                            inp.appendChild(o);
                        }
                        inp.value = layer.ctx[c.name];

                        inp.addEventListener('change', (e) => {
                            layer.ctx[c.name] = e.target.value;
                            code.textContent = layer.ctx.serialize(
                                nativeMode,
                                currentTimeMs,
                                code.classList.contains('collapsed'),
                                window.emitSequence.getNameAt(currentTimeMs));
                            requestAnimationFrame(draw);
                        });
                    } else {
                        inp = document.createElement('input');
                        if (c.min !== undefined) inp.min = c.min;
                        if (c.max !== undefined) {
                            if (inp.min === undefined) inp.min = 0;
                            inp.max = c.max;
                            inp.type = 'range';
                        } else if (c.min !== undefined) {
                            inp.type = 'number';
                        } else {
                            inp.type = 'text';
                        }
                        if (c.step !== undefined) inp.step = c.step;

                        inp.placeholder = c.name;
                        inp.value = layer.ctx[c.name] !== undefined ? layer.ctx[c.name] : 0;

                        inp.addEventListener('input', (e) => {
                            let text = e.target.value;
                            if (c.type === 'range') {
                                text = text.replace(/[^0-9.-]/g, '');
                            } else if (c.name === 'count') {
                                text = text.replace(/[^0-9]/g, '');
                            } else {
                                text = text.replace(/[^0-9.-]/g, '');
                            }
                            e.target.value = text;

                            let val = parseFloat(text);
                            if (!isNaN(val)) {
                                layer.ctx[c.name] = val;
                                code.textContent = layer.ctx.serialize(
                                    nativeMode,
                                    currentTimeMs,
                                    code.classList.contains('collapsed'),
                                    window.emitSequence.getNameAt(currentTimeMs));
                                requestAnimationFrame(draw);
                            }
                        });
                    }

                    inp.style.width = '80px';
                    inp.style.background = 'var(--bg-panel)';
                    inp.style.color = 'var(--text-color)';
                    inp.style.border = '1px solid var(--border-color)';
                    if (c.type !== 'color') {
                        inp.style.padding = '2px 4px';
                    }

                    inp.addEventListener('click', e => e.stopPropagation());

                    row.appendChild(lbl);
                    row.appendChild(inp);
                    controls.appendChild(row);
                }
                item.appendChild(controls);
            }

            item.addEventListener('click', () => {
                if (currentEmitIndex !== idx) {
                    currentEmitIndex = idx;
                    updateLayerDisplay();
                }
            });

            layerList.appendChild(item);
        });
    }

    function updateTimeline() {
        const container = document.getElementById('timeline-container');
        if (!container) return;

        container.innerHTML = '';

        // Collect all times that have emits
        const timesSet = new Set(
            Array.from(window.emitSequence._sequence.keys())
                 .filter(t => window.emitSequence.getEmitsAt(t).length > 0)
        );

        // Ensure current time is included
        timesSet.add(currentTimeMs);

        const times = Array.from(timesSet).sort((a, b) => a - b);

        for (const t of times) {
            const entry = document.createElement('div');
            entry.className = 'timeline-entry';
            if (t === currentTimeMs) {
                entry.classList.add('selected');
                // Scroll the selected entry into view smoothly
                setTimeout(() => {
                    entry.scrollIntoView({
                        behavior: 'smooth',
                        block: 'nearest',
                        inline: 'center'
                    });
                }, 0);
            }

            const timeLabel = document.createElement('div');
            let displayTime = Math.round(t);
            if (timeFormat === 'beat') {
                displayTime = (t / (60000 / tempo)).toFixed(2);
            } else if (timeFormat === 'frame') {
                displayTime = Math.round(t * fps / 1000);
            }
            timeLabel.textContent = displayTime;
            entry.appendChild(timeLabel);

            const name = window.emitSequence.getNameAt(t);
            if (name) {
                const nameLabel = document.createElement('div');
                nameLabel.textContent = name;
                nameLabel.style.fontSize = '10px';
                nameLabel.style.opacity = '0.7';
                nameLabel.style.whiteSpace = 'nowrap';
                nameLabel.style.overflow = 'hidden';
                nameLabel.style.textOverflow = 'ellipsis';
                nameLabel.style.maxWidth = '100px';
                entry.appendChild(nameLabel);
            }

            entry.addEventListener('click', () => {
                if (currentTimeMs !== t) {
                    saveCurrentFrame();
                    currentTimeMs = t;
                    loadCurrentFrame();
                    updateTimeUI();
                }
            });

            container.appendChild(entry);
        }
    }

    function updateTimeUI() {
        inputTime.value = Math.round(currentTimeMs);
        btnTimePrev.disabled = currentTimeMs <= 0;

        // Calculate and update frame number based on current time and FPS
        const frameNum = Math.round(currentTimeMs * fps / 1000);
        labelFrame.textContent = `Frame: ${frameNum}`;
        updateLayerDisplay();
        updateTimeline();
        requestAnimationFrame(draw);
    }

    selectFps.addEventListener('change', (e) => {
        fps = parseInt(e.target.value, 10);
        updateTimeUI();
    });

    function saveCurrentFrame() {
        emitSequence.setEmitsAt(currentTimeMs, [...currentEmits]);
    }

    function loadCurrentFrame() {
        const loaded = emitSequence.getEmitsAt(currentTimeMs);
        if (loaded.length > 0) {
            currentEmits = [...loaded];
            currentEmitIndex = 0;
        } else {
            currentEmits = [];
            currentEmitIndex = null;
        }
        inputFrameName.value = emitSequence.getNameAt(currentTimeMs) || "";
        inputFrameOffset.value = Math.round(currentTimeMs);
    }

    function exportData() {
        saveCurrentFrame();

        const data = {
            canvasW,
            canvasH,
            tempo,
            timeFormat,
            customScript,
            toggles: { showAxes, nativeMode, dragMode },
            frames: {},
            names: {}
        };

        for (const [time, builders] of emitSequence) {
            const ms = Math.floor(time);
            data.frames[ms] = builders.map(b => b.ctx.toJSON());
            data.names[ms] = emitSequence.getNameAt(time) || "";
        }
        const ms = Math.floor(currentTimeMs);
        if (!data.frames[ms]) {
            console.log(`Missed entry for ${ms}: ${currentTimeMs}`);
            data.frames[ms] = currentEmits.map(b => b.ctx.toJSON());
            data.names[ms] = emitSequence.getNameAt(currentTimeMs) || "";
        }

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'export.json';
        a.click();
        URL.revokeObjectURL(a.href);
    }

    btnTimePrev.addEventListener('click', () => {
        saveCurrentFrame();
        const step = 1000 / fps;
        currentTimeMs -= step;
        if (currentTimeMs < 0) currentTimeMs = 0;
        loadCurrentFrame();
        updateTimeUI();
    });

    btnTimeNext.addEventListener('click', () => {
        saveCurrentFrame();
        const step = 1000 / fps;
        currentTimeMs += step;
        loadCurrentFrame();
        updateTimeUI();
    });

    btnTimeSeekPrev.addEventListener('click', () => {
        saveCurrentFrame();
        const times = Array.from(window.emitSequence._sequence.keys())
            .filter(t => window.emitSequence.getEmitsAt(t).length > 0)
            .sort((a, b) => a - b);

        if (times.length === 0) return;
        if (times.length === 1 && times[0] === currentTimeMs) return;

        let target = times.slice().reverse().find(t => t < currentTimeMs);
        if (target === undefined) {
            target = times[times.length - 1]; // wrap around to largest
        }

        currentTimeMs = target;
        loadCurrentFrame();
        updateTimeUI();
    });

    btnTimeSeekNext.addEventListener('click', () => {
        saveCurrentFrame();
        const times = Array.from(window.emitSequence._sequence.keys())
            .filter(t => window.emitSequence.getEmitsAt(t).length > 0)
            .sort((a, b) => a - b);

        if (times.length === 0) return;
        if (times.length === 1 && times[0] === currentTimeMs) return;

        let target = times.find(t => t > currentTimeMs);
        if (target === undefined) {
            target = times[0]; // wrap around to smallest
        }

        currentTimeMs = target;
        loadCurrentFrame();
        updateTimeUI();
    });

    inputTime.addEventListener('change', (e) => {
        const val = parseFloat(e.target.value);
        if (!isNaN(val) && val >= 0) {
            saveCurrentFrame();
            currentTimeMs = val;
            loadCurrentFrame();
        }
        updateTimeUI();
    });

    inputTempo.addEventListener('change', (e) => {
        const val = parseFloat(e.target.value);
        if (!isNaN(val) && val > 0) {
            tempo = val;
            updateTimeUI();
        }
    });

    selectTimeFormat.addEventListener('change', (e) => {
        timeFormat = e.target.value;
        updateTimeUI();
    });

    // Initial UI update
    updateTimeUI();

    // Rendering loop
    function draw() {
        // Clear the canvas for the new frame
        ctx.clearRect(0, 0, canvas.width, canvas.height);

        // Center coordinates
        const cx = Math.floor(canvas.width / 2) + 0.5; // +0.5 for crisp 1px lines
        const cy = Math.floor(canvas.height / 2) + 0.5;

        // Draw a black box representing canvasW x canvasH
        ctx.fillStyle = 'black';
        ctx.fillRect(
            Math.floor(canvas.width / 2) - canvasW / 2,
            Math.floor(canvas.height / 2) - canvasH / 2,
            canvasW,
            canvasH);

        // Draw axes if enabled
        if (showAxes) {
            ctx.beginPath();
            ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)'; // Faint, visible white
            ctx.lineWidth = 1;

            // X-axis (horizontal)
            ctx.moveTo(0, cy);
            ctx.lineTo(canvas.width, cy);

            // Y-axis (vertical)
            ctx.moveTo(cx, 0);
            ctx.lineTo(cx, canvas.height);

            ctx.stroke();
        }

        for (const emit of currentEmits) {
            emit.draw(ctx);
        }
    }

    // Start rendering
    requestAnimationFrame(draw);

    // Mouse Events
    canvas.addEventListener('mousedown', (e) => {
        const cx = canvas.clientWidth / 2;
        const cy = canvas.clientHeight / 2;
        if (e.offsetX < cx - canvasW / 2 || e.offsetX > cx + canvasW / 2 ||
            e.offsetY < cy - canvasH / 2 || e.offsetY > cy + canvasH / 2) {
            return;
        }

        if (dragMode) {
            saveStateForUndo();
            isDraggingCanvas = true;

            lastDragPos = { x: 0, y: 0 };
            lastDragPos.x = Math.round((e.offsetX / canvas.clientWidth) * (2 * canvasW) - canvasW);
            lastDragPos.y = Math.round((e.offsetY / canvas.clientHeight) * (2 * canvasH) - canvasH);
        } else {
            const builder = window.currentEmits[currentEmitIndex];
            if (builder) {
                builder.mouseDown(e);
            }
        }
        requestAnimationFrame(draw);
    });

    canvas.addEventListener('mousemove', (e) => {
        const cx = canvas.clientWidth / 2;
        const cy = canvas.clientHeight / 2;
        if (e.offsetX < cx - canvasW / 2 || e.offsetX > cx + canvasW / 2 ||
            e.offsetY < cy - canvasH / 2 || e.offsetY > cy + canvasH / 2) {
            statusCursor.textContent = "Outside Canvas";
            return;
        }

        let mapPos = { x: 0, y: 0 };
        mapPos.x = Math.round((e.offsetX / canvas.clientWidth) * (2 * canvasW) - canvasW);
        mapPos.y = Math.round((e.offsetY / canvas.clientHeight) * (2 * canvasH) - canvasH);

        statusCursor.textContent = `${mapPos.x} , ${mapPos.y}`;

        const builder = currentEmits[currentEmitIndex];
        if (dragMode && isDraggingCanvas && lastDragPos && builder) {
            const dx = mapPos.x - lastDragPos.x;
            const dy = mapPos.y - lastDragPos.y;
            builder.ctx.x += dx;
            builder.ctx.y += dy;
            lastDragPos = mapPos;

            // Update code display in real time without tearing down DOM
            const codeElements = document.querySelectorAll('.layer-code');
            const currentLayer = codeElements[currentEmitIndex];
            if (currentLayer) {
                currentLayer.textContent =
                    builder.ctx.serialize(
                        nativeMode,
                        currentTimeMs,
                        currentLayer.classList.contains('collapsed'),
                        window.emitSequence.getNameAt(currentTimeMs)
                    );
            }

            requestAnimationFrame(draw);
        } else if (builder && builder.dragging) {
            builder.mouseMove(e);
            updateLayerDisplay();
            requestAnimationFrame(draw);
        }
    });

    canvas.addEventListener('mouseup', (e) => {
        if (dragMode && isDraggingCanvas) {
            isDraggingCanvas = false;
            lastDragPos = null;
            updateLayerDisplay(); // Refresh UI inputs on drop
        } else {
            const builder = window.currentEmits[currentEmitIndex];
            if (builder && builder.dragging) {
                builder.mouseUp(e);
            }
            requestAnimationFrame(draw);
        }
    });

    canvas.addEventListener('mouseleave', () => {
        if (dragMode && isDraggingCanvas) {
            isDraggingCanvas = false;
            lastDragPos = null;
            updateLayerDisplay();
        }
        statusCursor.textContent = `- , -`;
    });

    canvas.addEventListener('keyup', (e) => {
        console.log(`Key up: ${e.key} (Code: ${e.code})`);
    });

    function onLoad(file) {
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const data = JSON.parse(e.target.result);

                if (data.canvasW) canvasW = data.canvasW;
                if (data.canvasH) canvasH = data.canvasH;
                inputCanvasW.value = canvasW;
                inputCanvasH.value = canvasH;

                if (data.tempo !== undefined) {
                    tempo = data.tempo;
                } else {
                    tempo = DEFAULT_TEMPO;
                }
                if (inputTempo) inputTempo.value = tempo;

                if (data.timeFormat !== undefined) {
                    timeFormat = data.timeFormat;
                    if (selectTimeFormat) selectTimeFormat.value = timeFormat;
                }

                if (data.customScript !== undefined) {
                    customScript = data.customScript;
                } else {
                    customScript = TEMPLATE_SCRIPT;
                }
                const scriptTextarea = document.getElementById('script-textarea');
                if (scriptTextarea) scriptTextarea.value = customScript;

                if (data.toggles) {
                    showAxes = !!data.toggles.showAxes;
                    nativeMode = !!data.toggles.nativeMode;
                    dragMode = !!data.toggles.dragMode;

                    document.getElementById('btn-axes').classList.toggle('active', showAxes);
                    document.getElementById('btn-native').classList.toggle('active', nativeMode);
                    document.getElementById('btn-drag').classList.toggle('active', dragMode);
                }

                emitSequence.clear();
                if (data.frames) {
                    for (const [timeStr, contexts] of Object.entries(data.frames)) {
                        const time = parseInt(timeStr, 10);
                        const builders = contexts.map(ctxData => {
                            const builder = new EmitBuilder(canvas, canvasW, canvasH);
                            builder.ctx = EmitContext.FromJSON(ctxData);
                            return builder;
                        });
                        emitSequence.setEmitsAt(time, builders);
                        if (data.names && data.names[timeStr]) {
                            emitSequence.setNameAt(time, data.names[timeStr]);
                        }
                    }
                }

                loadCurrentFrame();
                updateTimeUI();
                requestAnimationFrame(draw);

                console.log('Loaded JSON successfully.');
            } catch (error) {
                console.error('Failed to parse JSON:', error);
                alert('Failed to parse JSON: ' + error.message);
            }
        };
        reader.readAsText(file);
    }

    function openJsonFile() {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = '.json';
        input.multiple = false;
        input.onchange = (e) => {
            const file = e.target.files[0];
            if (file) {
                onLoad(file);
            }
        };
        input.click();
    }

    // Toolbar Button Click Events
    const buttons = document.querySelectorAll('.btn');
    buttons.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const btnName = btn.title || btn.textContent.trim();
            console.log(`Button clicked: ${btnName}`);

            // Handle tool buttons (exclusive toggle)
            if (btn.classList.contains('tool-btn')) {
                // Disable all other buttons first
                document.querySelectorAll('.tool-btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');

                if (btn.id === 'tool-square') {
                    currentToolMode = ToolMode.SQUARE;
                } else if (btn.id === 'tool-circle') {
                    currentToolMode = ToolMode.CIRCLE;
                }
                currentEmits[currentEmitIndex].mode = currentToolMode;

                console.log(`Tool mode changed to: ${currentToolMode}`);
            }
            // Handle regular toggle buttons
            else if (btn.classList.contains('toggle-btn')) {
                btn.classList.toggle('active');
            }

            // Handle other buttons
            switch (btn.id) {
                case 'btn-axes':
                    showAxes = btn.classList.contains('active');
                    requestAnimationFrame(draw);
                    break;
                case 'btn-native':
                    nativeMode = btn.classList.contains('active');
                    document.querySelectorAll('.layer-code').forEach((codeEl, i) => {
                        if (currentEmits[i]) {
                            codeEl.textContent = currentEmits[i].ctx.serialize(
                                nativeMode,
                                currentTimeMs,
                                codeEl.classList.contains('collapsed'),
                                window.emitSequence.getNameAt(currentTimeMs));
                        }
                    });
                    requestAnimationFrame(draw);
                    break;
                case 'btn-drag':
                    dragMode = btn.classList.contains('active');
                    requestAnimationFrame(draw);
                    break;
            }
        });
    });

    const btnMirror = document.getElementById('btn-mirror');
    btnMirror.addEventListener('click', () => {
        if (currentEmitIndex !== null && currentEmits[currentEmitIndex]) {
            saveStateForUndo();
            const original = currentEmits[currentEmitIndex];
            const mirrored = new EmitBuilder(canvas, canvasW, canvasH);
            mirrored.ctx = EmitContext.FromJSON(original.ctx.toJSON());

            mirrored.ctx.x = -mirrored.ctx.x;
            mirrored.ctx.theta = Math.PI - mirrored.ctx.theta;

            // Normalize theta to [0, 2pi) range
            while (mirrored.ctx.theta < 0) mirrored.ctx.theta += 2 * Math.PI;
            while (mirrored.ctx.theta >= 2 * Math.PI) mirrored.ctx.theta -= 2 * Math.PI;

            currentEmits.push(mirrored);
            currentEmitIndex = currentEmits.length - 1;
            updateLayerDisplay();
        }
        requestAnimationFrame(draw);
    });

    const btnAddLayer = document.getElementById('btn-add-layer');
    btnAddLayer.addEventListener('click', () => {
        saveStateForUndo();
        currentEmits.push(new EmitBuilder(canvas, canvasW, canvasH));
        currentEmitIndex = currentEmits.length - 1;
        console.log(`Added new emit layer. Now editing layer ${currentEmitIndex}`);
        updateLayerDisplay();
    });

    const btnCopyFrame = document.getElementById('btn-copy-frame');
    btnCopyFrame.addEventListener('click', () => {
        if (currentEmitIndex !== null && currentEmits[currentEmitIndex]) {
            clipboardFrame = currentEmits.map(b => b.ctx.toJSON());
            console.log(`Copied ${clipboardFrame.length} emits to clipboard.`);
        } else {
            console.log('No emits to copy.');
            clipboardFrame = null;
        }
    });

    const btnPasteFrame = document.getElementById('btn-paste-frame');
    btnPasteFrame.addEventListener('click', () => {
        if (clipboardFrame) {
            saveStateForUndo();
            for (const data of clipboardFrame) {
                const builder = new EmitBuilder(canvas, canvasW, canvasH);
                builder.ctx = EmitContext.FromJSON(data);
                currentEmits.push(builder);
            }
            if (currentEmitIndex === null || currentEmits.length > 0) {
                currentEmitIndex = currentEmits.length - 1;
            }
            updateLayerDisplay();
            requestAnimationFrame(draw);
            console.log(`Pasted ${clipboardFrame.length} emits from clipboard.`);
        } else {
            console.log('Clipboard is empty.');
        }
    });

    const btnDeleteFrame = document.getElementById('btn-delete-frame');
    btnDeleteFrame.addEventListener('click', () => {
        saveStateForUndo();
        window.emitSequence.deleteAt(currentTimeMs);
        currentEmits = [];
        currentEmitIndex = null;

        const times = Array.from(window.emitSequence._sequence.keys())
            .filter(t => window.emitSequence.getEmitsAt(t).length > 0)
            .sort((a, b) => a - b);

        if (times.length > 0) {
            let target = times.find(t => t > currentTimeMs);
            if (target === undefined) {
                target = times[0]; // wrap around
            }
            currentTimeMs = target;
        }
        loadCurrentFrame();
        updateTimeUI();
    });

    const btnLoad = document.getElementById('btn-load');
    btnLoad.addEventListener('click', () => {
        openJsonFile();
    });

    const btnSave = document.getElementById('btn-save');
    btnSave.addEventListener('click', () => {
        console.log('Save button clicked');
        exportData();
    });

    const btnExport = document.getElementById('btn-export');
    btnExport.addEventListener('click', () => {
        console.log('Export button clicked');
        saveCurrentFrame();
        let luaContent = customScript;
        if (!luaContent.endsWith('\n')) luaContent += '\n';
        for (const [time, builders] of window.emitSequence) {
            const frameName = window.emitSequence.getNameAt(time);
            for (const builder of builders) {
                luaContent += builder.ctx.serialize(nativeMode, time, false, frameName) + "\n";
            }
        }
        const blob = new Blob([luaContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'sequence.lua';
        a.click();
        URL.revokeObjectURL(url);
    });

    const btnUndo = document.getElementById('btn-undo');
    btnUndo.addEventListener('click', () => {
        performUndo();
        console.log('Undo button clicked');
    });

    const btnRedo = document.getElementById('btn-redo');
    btnRedo.addEventListener('click', () => {
        performRedo();
        console.log('Redo button clicked');
    });

    const btnAutoLifetime = document.getElementById('btn-auto-lifetime');
    if (btnAutoLifetime) {
        btnAutoLifetime.addEventListener('click', () => {
            saveStateForUndo();
            saveCurrentFrame();

            const times = Array.from(window.emitSequence._sequence.keys()).sort((a, b) => a - b);
            for (let i = 0; i < times.length - 1; i++) {
                const currentT = times[i];
                const nextT = times[i + 1];
                const diff = nextT - currentT;
                const emits = window.emitSequence.getEmitsAt(currentT);
                emits.forEach((builder) => {
                    builder.ctx.life = diff;
                });
            }

            loadCurrentFrame();
            updateTimeUI();
            updateLayerDisplay();
            requestAnimationFrame(draw);
            console.log('Auto-populated particle lifetimes.');
        });
    }

    const btnAutoTag = document.getElementById('btn-auto-tag');
    if (btnAutoTag) {
        btnAutoTag.addEventListener('click', () => {
            saveStateForUndo();
            saveCurrentFrame();

            const times = Array.from(window.emitSequence._sequence.keys()).sort((a, b) => a - b);
            for (let i = 0; i < times.length; i++) {
                const currentT = times[i];
                const emits = window.emitSequence.getEmitsAt(currentT);
                const label = window.emitSequence.getNameAt(currentT);
                emits.forEach((builder, layerIndex) => {
                    const oldTag = builder.ctx.tag;
                    builder.ctx.tag = currentT;
                    console.log(`Frame "${label}" at ${currentT}ms, Layer ${layerIndex}: updated tag from ${oldTag} to ${currentT}`);
                });
            }

            loadCurrentFrame();
            updateTimeUI();
            updateLayerDisplay();
            requestAnimationFrame(draw);
            console.log('Auto-populated particle tags.');
        });
    }

    const btnImportTiming = document.getElementById('btn-import-timing');
    btnImportTiming.addEventListener('click', () => {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = '.csv';
        input.multiple = false;
        input.onchange = (e) => {
            const file = e.target.files[0];
            if (file) {
                Papa.parse(file, {
                    header: true,
                    skipEmptyLines: true,
                    complete: function(results) {
                        const data = results.data;
                        if (data.length === 0) return;

                        if (!results.meta.fields.includes('t(msec)') || !results.meta.fields.includes('dur(msec)')) {
                            alert('CSV must contain "t(msec)" and "dur(msec)" columns');
                            return;
                        }

                        saveStateForUndo();

                        for (const row of data) {
                            const tStr = row['t(msec)'];
                            const durStr = row['dur(msec)'];
                            if (tStr === undefined || durStr === undefined) continue;

                            const t = parseFloat(String(tStr).trim());
                            const dur = parseFloat(String(durStr).trim());

                            if (!isNaN(t) && !isNaN(dur)) {
                                if (!window.emitSequence.exists(t)) {
                                    const builder = new EmitBuilder(canvas, canvasW, canvasH);
                                    builder.ctx.life = dur;
                                    window.emitSequence.setEmitsAt(t, [builder]);
                                } else {
                                    const emits = window.emitSequence.getEmitsAt(t);
                                    for (const emit of emits) {
                                        emit.ctx.life = dur;
                                    }
                                }

                                if (row['lyric']) {
                                    const lyric = String(row['lyric']).trim();
                                    if (lyric) {
                                        window.emitSequence.setNameAt(t, lyric);
                                    }
                                }
                            }
                        }

                        const times = Array.from(window.emitSequence._sequence.keys()).sort((a, b) => a - b);
                        if (times.length > 0) {
                            currentTimeMs = times[0];
                        }
                        loadCurrentFrame();
                        updateTimeUI();
                    }
                });
            }
        };
        input.click();
    });

    // Theta Modal Logic
    let activeThetaLayer = null;
    let activeThetaCode = null;

    function drawThetaCanvas(theta, utheta) {
        if (!thetaCanvas) return;
        const ctx = thetaCanvas.getContext('2d');
        const w = thetaCanvas.width;
        const h = thetaCanvas.height;
        const cx = w / 2;
        const cy = h / 2;
        const r = Math.min(cx, cy) - 10;

        ctx.clearRect(0, 0, w, h);

        // Draw background circle
        ctx.beginPath();
        ctx.arc(cx, cy, r, 0, 2 * Math.PI);
        ctx.fillStyle = 'rgba(255, 255, 255, 0.05)';
        ctx.fill();
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.2)';
        ctx.lineWidth = 2;
        ctx.stroke();

        // Shade wedge around theta
        ctx.beginPath();
        ctx.moveTo(cx, cy);
        ctx.arc(cx, cy, r, theta - utheta, theta + utheta, false);
        ctx.closePath();
        ctx.fillStyle = 'rgba(0, 255, 0, 0.3)';
        ctx.fill();
        
        ctx.strokeStyle = 'var(--accent-color)';
        ctx.lineWidth = 2;
        ctx.stroke();

        // Draw center line for theta
        const ex = cx + r * Math.cos(theta);
        const ey = cy + r * Math.sin(theta);
        ctx.beginPath();
        ctx.moveTo(cx, cy);
        ctx.lineTo(ex, ey);
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.5)';
        ctx.lineWidth = 1;
        ctx.stroke();

        // Draw center dot
        ctx.beginPath();
        ctx.arc(cx, cy, 4, 0, 2 * Math.PI);
        ctx.fillStyle = 'var(--accent-color)';
        ctx.fill();
    }

    function updateModalValue(property, val) {
        if (!activeThetaLayer) return;
        let rad = parseFloat(val);
        if (isNaN(rad)) return;

        if (property === 'theta') {
            while (rad < 0) rad += 2 * Math.PI;
            while (rad >= 2 * Math.PI) rad -= 2 * Math.PI;
        } else if (property === 'utheta') {
            if (rad < 0) rad = 0;
            if (rad > Math.PI) rad = Math.PI;
        }

        activeThetaLayer.ctx[property] = rad;
        
        const currentTheta = activeThetaLayer.ctx.theta || 0;
        const currentUTheta = activeThetaLayer.ctx.utheta || 0;
        drawThetaCanvas(currentTheta, currentUTheta);

        if (activeThetaCode) {
            activeThetaCode.textContent = activeThetaLayer.ctx.serialize(
                nativeMode,
                currentTimeMs,
                activeThetaCode.classList.contains('collapsed'),
                window.emitSequence.getNameAt(currentTimeMs));
        }

        requestAnimationFrame(draw);
    }

    function openThetaModal(layer, codeElement) {
        if (!thetaModal) return;
        activeThetaLayer = layer;
        activeThetaCode = codeElement;

        const thetaAngle = layer.ctx.theta || 0;
        const uthetaAngle = layer.ctx.utheta || 0;
        
        thetaSlider.value = thetaAngle;
        thetaRadians.value = thetaAngle;
        thetaDegrees.value = Math.round(thetaAngle * 180 / Math.PI);

        uthetaSlider.value = uthetaAngle;
        uthetaRadians.value = uthetaAngle;
        uthetaDegrees.value = Math.round(uthetaAngle * 180 / Math.PI);

        thetaModal.style.display = 'flex';
        drawThetaCanvas(thetaAngle, uthetaAngle);
    }
    thetaSlider.addEventListener('input', (e) => {
        const rad = parseFloat(e.target.value);
        thetaDegrees.value = Math.round(rad * 180 / Math.PI);
        thetaRadians.value = rad;
        updateModalValue('theta', rad);
    });

    thetaRadians.addEventListener('input', (e) => {
        try {
            const rad = math.evaluate(e.target.value);
            thetaSlider.value = rad;
            thetaDegrees.value = Math.round(rad * 180 / Math.PI);
            updateModalValue('theta', rad);
        } catch (error) {
            console.error("Failed to evaluate theta input:", error);
        }
    });

    thetaDegrees.addEventListener('input', (e) => {
        try {
            const deg = math.evaluate(e.target.value);
            const rad = deg * Math.PI / 180;
            thetaSlider.value = rad;
            thetaRadians.value = rad;
            updateModalValue('theta', rad);
        } catch (error) {
            console.error("Failed to evaluate theta input:", error);
        }
    });

    uthetaSlider.addEventListener('input', (e) => {
        const rad = parseFloat(e.target.value);
        uthetaDegrees.value = Math.round(rad * 180 / Math.PI);
        uthetaRadians.value = rad;
        updateModalValue('utheta', rad);
    });

    uthetaRadians.addEventListener('input', (e) => {
        try {
            const rad = math.evaluate(e.target.value);
            uthetaSlider.value = rad;
            uthetaDegrees.value = Math.round(rad * 180 / Math.PI);
            updateModalValue('utheta', rad);
        } catch (error) {
            console.error("Failed to evaluate utheta input:", error);
        }
    });

    uthetaDegrees.addEventListener('input', (e) => {
        try {
            const deg = math.evaluate(e.target.value);
            const rad = deg * Math.PI / 180;
            uthetaSlider.value = rad;
            uthetaRadians.value = rad;
            updateModalValue('utheta', rad);
        } catch (error) {
            console.error("Failed to evaluate utheta input:", error);
        }
    });

    thetaModal.addEventListener('click', (e) => {
        if (e.target === thetaModal) {
            thetaModal.style.display = 'none';
            updateLayerDisplay(); // Refresh the main panel inputs
        }
    });

    const scriptModal = document.getElementById('script-modal');
    const scriptTextarea = document.getElementById('script-textarea');
    const btnCustomScript = document.getElementById('btn-custom-script');

    if (btnCustomScript && scriptModal && scriptTextarea) {
        btnCustomScript.addEventListener('click', () => {
            scriptTextarea.value = customScript;
            scriptModal.style.display = 'flex';
        });

        scriptTextarea.addEventListener('input', (e) => {
            customScript = e.target.value;
        });

        scriptModal.addEventListener('click', (e) => {
            if (e.target === scriptModal) {
                scriptModal.style.display = 'none';
            }
        });
    }

    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' || e.key === 'Enter') {
            if (thetaModal && thetaModal.style.display === 'flex') {
                thetaModal.style.display = 'none';
                updateLayerDisplay(); // Refresh the main panel inputs
            }
            if (scriptModal && scriptModal.style.display === 'flex') {
                scriptModal.style.display = 'none';
            }
        }
    });

    // Ensure canvas has focus so keyboard shortcuts work immediately after a page reload
    canvas.focus();
});

// vim: set ts=4 sts=4 sw=4:
